// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_AbVPkhf-nnGlo0EQ-gR2-drm5Mp8JJI',
    appId: '1:339922420964:web:cf5a68342fe54e188e18f1',
    messagingSenderId: '339922420964',
    projectId: 'workshop-2-26086',
    authDomain: 'workshop-2-26086.firebaseapp.com',
    storageBucket: 'workshop-2-26086.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUqyOYlX75HTRI7L6tKeOCpLWblh24MI8',
    appId: '1:339922420964:android:b6770ce65dfce0998e18f1',
    messagingSenderId: '339922420964',
    projectId: 'workshop-2-26086',
    storageBucket: 'workshop-2-26086.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1sKgaFhixzCdnLTlT-CX2EDQqBOg0vFo',
    appId: '1:339922420964:ios:ac62b5d1120df3b38e18f1',
    messagingSenderId: '339922420964',
    projectId: 'workshop-2-26086',
    storageBucket: 'workshop-2-26086.appspot.com',
    iosBundleId: 'com.example.mockapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1sKgaFhixzCdnLTlT-CX2EDQqBOg0vFo',
    appId: '1:339922420964:ios:d8ea4915727d68b18e18f1',
    messagingSenderId: '339922420964',
    projectId: 'workshop-2-26086',
    storageBucket: 'workshop-2-26086.appspot.com',
    iosBundleId: 'com.example.mockapp.RunnerTests',
  );
}
